### ISSUE TITLE
Scala 3 checklist

### ISSUE THREAD

**Issue by kubukoz** [kubukoz/spotify-next#196]
- [ ] decline (awaiting 3.x release)
- [x] removing circe-literal
- [x] better-monadic-for replacement: looks like we don't have any recursion in `for`, so it's not a problem
